name: test-action
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '30 8 * * *'

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker image pull ghcr.io/timarenz/vulnerable-container:v0.0.1

      - name: lw-scanner
        id: lw-scanner
        uses: ./
        with:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          IMAGE_NAME: ghcr.io/timarenz/vulnerable-container
          IMAGE_TAG: v0.0.1
          SAVE_RESULTS_IN_LACEWORK: true
          SAVE_BUILD_REPORT: true
          BUILD_REPORT_FILE_NAME: myreport.html
          FAIL_BUILD: true
          SEVERITY_THRESHOLD: fixable
